#ifndef __MCMAP_HEADER
#define __MCMAP_HEADER

#define MCMAP_MAXNAME 2048

//minecraft data values
typedef enum
	{
	MCMAP_AIR                     =   0,
	MCMAP_STONE                   =   1,
	MCMAP_GRASS                   =   2,
	MCMAP_DIRT                    =   3,
	MCMAP_COBBLESTONE             =   4,
	MCMAP_WOOD_PLANKS             =   5,
	MCMAP_SAPLING                 =   6,
	MCMAP_BEDROCK                 =   7,
	MCMAP_FLOWING_WATER           =   8,
	MCMAP_WATER                   =   9,
	MCMAP_FLOWING_LAVA            =  10,
	MCMAP_LAVA                    =  11,
	MCMAP_SAND                    =  12,
	MCMAP_GRAVEL                  =  13,
	MCMAP_GOLD_ORE                =  14,
	MCMAP_IRON_ORE                =  15,
	MCMAP_COAL_ORE                =  16,
	MCMAP_WOOD                    =  17,
	MCMAP_LEAVES                  =  18,
	MCMAP_SPONGE                  =  19,
	MCMAP_GLASS                   =  20,
	MCMAP_LAPIS_ORE               =  21,
	MCMAP_LAPIS_BLOCK             =  22,
	MCMAP_DISPENSER               =  23,
	MCMAP_SANDSTONE               =  24,
	MCMAP_NOTE_BLOCK              =  25,
	MCMAP_BED                     =  26,
	MCMAP_POWERED_RAIL            =  27,
	MCMAP_DETECTOR_RAIL           =  28,
	MCMAP_STICKY_PISTON           =  29,
	MCMAP_COBWEB                  =  30,
	MCMAP_TALL_GRASS              =  31,
	MCMAP_DEAD_BUSH               =  32,
	MCMAP_PISTON                  =  33,
	MCMAP_PISTON_EXT              =  34,
	MCMAP_WOOL                    =  35,
	MCMAP_MOVED_BY_PISTON         =  36,
	MCMAP_DANDELION               =  37,
	MCMAP_ROSE                    =  38,
	MCMAP_BROWN_MUSHROOM          =  39,
	MCMAP_RED_MUSHROOM            =  40,
	MCMAP_GOLD_BLOCK              =  41,
	MCMAP_IRON_BLOCK              =  42,
	MCMAP_DOUBLE_SLAB             =  43,
	MCMAP_SLAB                    =  44,
	MCMAP_BRICKS                  =  45,
	MCMAP_TNT                     =  46,
	MCMAP_BOOKSHELF               =  47,
	MCMAP_MOSS_STONE              =  48,
	MCMAP_OBSIDIAN                =  49,
	MCMAP_TORCH                   =  50,
	MCMAP_FIRE                    =  51,
	MCMAP_SPAWNER                 =  52,
	MCMAP_OAK_WOOD_STAIRS         =  53,
	MCMAP_CHEST                   =  54,
	MCMAP_REDSTONE_WIRE           =  55,
	MCMAP_DIAMOND_ORE             =  56,
	MCMAP_DIAMOND_BLOCK           =  57,
	MCMAP_CRAFTING_TABLE          =  58,
	MCMAP_WHEAT                   =  59,
	MCMAP_FARMLAND                =  60,
	MCMAP_FURNACE                 =  61,
	MCMAP_LIT_FURNACE             =  62,
	MCMAP_SIGN                    =  63,
	MCMAP_WOOD_DOOR               =  64,
	MCMAP_LADDER                  =  65,
	MCMAP_RAIL                    =  66,
	MCMAP_COBBLESTONE_STAIRS      =  67,
	MCMAP_WALL_SIGN               =  68,
	MCMAP_LEVER                   =  69,
	MCMAP_STONE_PRESSURE_PLATE    =  70,
	MCMAP_IRON_DOOR               =  71,
	MCMAP_WOOD_PRESSURE_PLATE     =  72,
	MCMAP_REDSTONE_ORE            =  73,
	MCMAP_GLOWING_REDSTONE_ORE    =  74,
	MCMAP_UNLIT_REDSTONE_TORCH    =  75,
	MCMAP_LIT_REDSTONE_TORCH      =  76,
	MCMAP_STONE_BUTTON            =  77,
	MCMAP_SNOW                    =  78,
	MCMAP_ICE                     =  79,
	MCMAP_SNOW_BLOCK              =  80,
	MCMAP_CACTUS                  =  81,
	MCMAP_CLAY_BLOCK              =  82,
	MCMAP_SUGAR_CANE              =  83,
	MCMAP_JUKEBOX                 =  84,
	MCMAP_FENCE                   =  85,
	MCMAP_PUMPKIN                 =  86,
	MCMAP_NETHERRACK              =  87,
	MCMAP_SOUL_SAND               =  88,
	MCMAP_GLOWSTONE               =  89,
	MCMAP_NETHER_PORTAL           =  90,
	MCMAP_JACK_O_LANTERN          =  91,
	MCMAP_PLACED_CAKE             =  92,
	MCMAP_UNLIT_REDSTONE_REPEATER =  93,
	MCMAP_LIT_REDSTONE_REPEATER   =  94,
	MCMAP_LOCKED_CHEST            =  95,
	MCMAP_TRAPDOOR                =  96,
	MCMAP_SILVERFISH_EGG          =  97,
	MCMAP_STONE_BRICKS            =  98,
	MCMAP_HUGE_BROWN_MUSHROOM     =  99,
	MCMAP_HUGE_RED_MUCHROOM       = 100,
	MCMAP_IRON_BARS               = 101,
	MCMAP_GLASS_PANE              = 102,
	MCMAP_MELON                   = 103,
	MCMAP_PUMPKIN_STEM            = 104,
	MCMAP_MELON_STEM              = 105,
	MCMAP_VINES                   = 106,
	MCMAP_GATE                    = 107,
	MCMAP_BRICK_STAIRS            = 108,
	MCMAP_STONE_BRICK_STAIRS      = 109,
	MCMAP_MYCELIUM                = 110,
	MCMAP_LILY_PAD                = 111,
	MCMAP_NETHER_BRICK            = 112,
	MCMAP_NETHER_BRICK_FENCE      = 113,
	MCMAP_NETHER_BRICK_STAIRS     = 114,
	MCMAP_NETHER_WART             = 115,
	MCMAP_ENCHANTING_TABLE        = 116,
	MCMAP_BREWING_STAND           = 117,
	MCMAP_CAULDRON                = 118,
	MCMAP_END_PORTAL              = 119,
	MCMAP_END_PORTAL_FRAME        = 120,
	MCMAP_END_STONE               = 121,
	MCMAP_DRAGON_EGG              = 122,
	MCMAP_UNLIT_REDSTONE_LAMP     = 123,
	MCMAP_LIT_REDSTONE_LAMP       = 124,
	MCMAP_WOOD_DOUBLE_SLAB        = 125,
	MCMAP_WOOD_SLAB               = 126,
	MCMAP_COCOA_POD               = 127,
	MCMAP_SANDSTONE_STAIRS        = 128,
	MCMAP_EMERALD_ORE             = 129,
	MCMAP_ENDER_CHEST             = 130,
	MCMAP_TRIPWIRE_HOOK           = 131,
	MCMAP_TRIPWIRE                = 132,
	MCMAP_EMERALD_BLOCK           = 133,
	MCMAP_SPRUCE_WOOD_STAIRS      = 134,
	MCMAP_BIRCH_WOOD_STAIRS       = 135,
	MCMAP_JUNGLE_WOOD_STAIRS      = 136,
	MCMAP_COMMAND_BLOCK           = 137,
	MCMAP_BEACON                  = 138,
	MCMAP_COBBLESTONE_WALL        = 139,
	MCMAP_FLOWER_POT              = 140,
	MCMAP_CARROTS                 = 141,
	MCMAP_POTATOES                = 142,
	MCMAP_WOOD_BUTTON             = 143,
	MCMAP_HEAD                    = 144,
	MCMAP_ANVIL                   = 145
	} mcmap_blockid;
typedef enum
	{
	MCMAP_NOBIOME             = -1,
	MCMAP_OCEAN               =  0,
	MCMAP_PLAINS              =  1,
	MCMAP_DESERT              =  2,
	MCMAP_EXTREME_HILLS       =  3,
	MCMAP_FOREST              =  4,
	MCMAP_TAIGA               =  5,
	MCMAP_SWAMPLAND           =  6,
	MCMAP_RIVER               =  7,
	MCMAP_HELL                =  8,
	MCMAP_SKY                 =  9,
	MCMAP_FROZENOCEAN         = 10,
	MCMAP_FROZENRIVER         = 11,
	MCMAP_ICE_PLAINS          = 12,
	MCMAP_ICE_MOUNTAINS       = 13,
	MCMAP_MUSHROOMISLAND      = 14,
	MCMAP_MUSHROOMISLANDSHORE = 15,
	MCMAP_BEACH               = 16,
	MCMAP_DESERTHILLS         = 17,
	MCMAP_FORESTHILLS         = 18,
	MCMAP_TAIGAHILLS          = 19,
	MCMAP_EXTREME_HILLS_EDGE  = 20,
	MCMAP_JUNGLE              = 21,
	MCMAP_JUNGLEHILLS         = 22
	} mcmap_biomeid;

//interpreted map structures
struct mcmap_region
	{
	unsigned char ***chunks;
	unsigned int dates[32][32];
	int lengths[32][32];
	unsigned char compression_type[32][32];
	};
struct mcmap_chunk
	{
	mcmap_blockid blocks[256][16][16];
	mcmap_biomeid biomes[16][16];
	unsigned char data[256][16][16];
	};

//searches the given path to a minecraft map folder and parses the region file for the given X & Z region coordinates
struct mcmap_region *mcmap_read_region(int, int, char *);

//free region memory structure
void mcmap_free_region(struct mcmap_region *);

struct mcmap_chunk *mcmap_read_chunk(int, int, struct mcmap_region *);

#endif
